/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ComoUsarRouteImport } from './routes/como-usar'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ContribuicoesRouteImport } from './routes/contribuicoes'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as DividasRouteImport } from './routes/dividas'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as RecebimentosFuturosRouteImport } from './routes/recebimentos-futuros'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoUsarRoute = ComoUsarRouteImport.update({
  id: '/como-usar',
  path: '/como-usar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuicoesRoute = ContribuicoesRouteImport.update({
  id: '/contribuicoes',
  path: '/contribuicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const DividasRoute = DividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentosFuturosRoute = RecebimentosFuturosRouteImport.update({
  id: '/recebimentos-futuros',
  path: '/recebimentos-futuros',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/como-usar': typeof ComoUsarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contribuicoes': typeof ContribuicoesRoute
  '/despesas': typeof DespesasRoute
  '/dividas': typeof DividasRoute
  '/historico': typeof HistoricoRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recebimentos-futuros': typeof RecebimentosFuturosRoute
  '/receitas': typeof ReceitasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/como-usar': typeof ComoUsarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contribuicoes': typeof ContribuicoesRoute
  '/despesas': typeof DespesasRoute
  '/dividas': typeof DividasRoute
  '/historico': typeof HistoricoRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recebimentos-futuros': typeof RecebimentosFuturosRoute
  '/receitas': typeof ReceitasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/como-usar': typeof ComoUsarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/contribuicoes': typeof ContribuicoesRoute
  '/despesas': typeof DespesasRoute
  '/dividas': typeof DividasRoute
  '/historico': typeof HistoricoRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recebimentos-futuros': typeof RecebimentosFuturosRoute
  '/receitas': typeof ReceitasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/categorias'
    | '/como-usar'
    | '/configuracoes'
    | '/contas'
    | '/contribuicoes'
    | '/despesas'
    | '/dividas'
    | '/historico'
    | '/planejamento'
    | '/recebimentos-futuros'
    | '/receitas'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/categorias'
    | '/como-usar'
    | '/configuracoes'
    | '/contas'
    | '/contribuicoes'
    | '/despesas'
    | '/dividas'
    | '/historico'
    | '/planejamento'
    | '/recebimentos-futuros'
    | '/receitas'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/categorias'
    | '/como-usar'
    | '/configuracoes'
    | '/contas'
    | '/contribuicoes'
    | '/despesas'
    | '/dividas'
    | '/historico'
    | '/planejamento'
    | '/recebimentos-futuros'
    | '/receitas'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CategoriasRoute: typeof CategoriasRoute
  ComoUsarRoute: typeof ComoUsarRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  ContribuicoesRoute: typeof ContribuicoesRoute
  DespesasRoute: typeof DespesasRoute
  DividasRoute: typeof DividasRoute
  HistoricoRoute: typeof HistoricoRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  RecebimentosFuturosRoute: typeof RecebimentosFuturosRoute
  ReceitasRoute: typeof ReceitasRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-usar': {
      id: '/como-usar'
      path: '/como-usar'
      fullPath: '/como-usar'
      preLoaderRoute: typeof ComoUsarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribuicoes': {
      id: '/contribuicoes'
      path: '/contribuicoes'
      fullPath: '/contribuicoes'
      preLoaderRoute: typeof ContribuicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividas': {
      id: '/dividas'
      path: '/dividas'
      fullPath: '/dividas'
      preLoaderRoute: typeof DividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimentos-futuros': {
      id: '/recebimentos-futuros'
      path: '/recebimentos-futuros'
      fullPath: '/recebimentos-futuros'
      preLoaderRoute: typeof RecebimentosFuturosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CategoriasRoute: CategoriasRoute,
  ComoUsarRoute: ComoUsarRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  ContribuicoesRoute: ContribuicoesRoute,
  DespesasRoute: DespesasRoute,
  DividasRoute: DividasRoute,
  HistoricoRoute: HistoricoRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  RecebimentosFuturosRoute: RecebimentosFuturosRoute,
  ReceitasRoute: ReceitasRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
